vich_uploader:
    db_driver: orm
    mappings:
        maisonhote_images:
            uri_prefix: '%app.path.maisonhote_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.maisonhote_images%'

