vich_uploader:
    db_driver: orm
    mappings:
        hotel_images:
            uri_prefix:         '%app.path.hotel_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.hotel_images%'
