vich_uploader:
    db_driver: orm
    mappings:
        excursion_images:
            uri_prefix:         '%app.path.excursion_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.excursion_images%'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_images%'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            delete_on_remove: true
            delete_on_update: true 
